---
title: "Molecular Analysis"
author: "Nicolas Banholzer"
date: "2023-06-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries 

```{r}
library(tidyverse)
library(reshape2)
library(tidybayes)
library(lubridate)
library(scales)
library(rstan)
source("../utils/epi.r")
source("../utils/bayes.r")
source("../utils/plotting.r")
source("../utils/tex.r")
```

## Data 

```{r}
df <- readRDS("../data-clean/molecular.rds")
df_ll <- readRDS("../data-clean/molecular-long.rds")
df_network <- rbind(readxl::read_excel("../data-clean/transmission-network.xlsx", sheet = "A"),
                    readxl::read_excel("../data-clean/transmission-network.xlsx", sheet = "B")) %>%
  mutate(date_infection = gsub("2022", "2023", as.character(date_infection)))

# manually from file because it is only a few samples
air_samples <- matrix(
  c("B", "25-01-2023", "HRV", "Air",
    "A", "20-02-2023", "AdV", "Air",
    "B", "01-02-2023", "Flu B", "Filter", # we set the dates for the filter swabs to align with saliva
    "A", "27-02-2023", "CoV", "Filter",
    "A", "03-03-2023", "AdV", "Filter",
    "A", "08-03-2023", "HRV", "Filter"),
  ncol = 4, byrow = T
) %>%
  data.frame() %>%
  set_names(c("class", "date", "virus", "type")) %>%
  mutate(date = as.Date(date, format = "%d-%m-%Y"))
```

## Descriptives

### Line list

```{r}
line_list_dat <- df_ll %>%
  mutate(weekday = weekdays(date)) %>%
  dplyr::select(class, date, weekday, result, virus) %>%
  arrange(class, date) %>%
  as.matrix() %>%
  xtable::xtable()

print.xtable(line_list_dat,
             type = "latex",
             file = "../results/mol-data/line-list-data.tex",
             sanitize.text.function = identity,
             include.colnames = F,
             include.rownames = F,
             only.contents = T,
             hline.after = NULL)
```

### Number of positive samples

```{r}
# positive samples by study condition and week
df_pos <- df %>%
  mutate(week = week(date),
         week = week - min(week) + 1,
         week = ifelse(week > 4, week - 1, week)) %>%
  dplyr::select(aircleaner, week, class, AdV, `Flu B`, HRV, MPV, PIV, `SARS-CoV-2`) %>%
  melt(c("aircleaner", "week", "class")) %>%
  group_by(aircleaner, class, week, variable) %>%
  summarize(n = sum(value)) %>%
  ungroup() %>%
  mutate(variable = as.character(variable), 
         variable = ifelse(variable == "SARS-CoV-2", "CoV", variable),
         variable = factor(variable, levels = c("Flu B", "HRV", "AdV", "CoV", "MPV", "PIV")),
         class = paste("Class", class)) %>%
  arrange(class, week, desc(variable))
```

```{r}
pos_week_pl <- ggplot(mapping = aes(x = week, y = n)) +
  facet_wrap(~ class) +
  geom_bar(data = df_pos, mapping = aes(fill = variable),
           stat = "identity", position = "stack") +
  geom_text(data = subset(df_pos, n > 0), mapping = aes(label = n), 
            size = 8 / cm(1), position = position_stack(vjust = 0.5), color = "white") +
  geom_text(
    data = data.frame(class = c("Class A", "Class B"), axis_title = c("Study week", "Study week")),
    mapping = aes(label = axis_title), hjust = 0.5, vjust = 3.5,
    x = min(df_pos$week) + diff(range(df_pos$week)) / 2,
    y = -Inf, color = 'black', size = 8 / cm(1)
  ) +
  scale_fill_manual(values = wes_palette("IsleofDogs1")) +
  scale_y_continuous(expand = expansion(add = c(0,1)), breaks = scales::breaks_width(2)) +
  scale_x_continuous(breaks = seq(1, 7, 1)) +
  labs(y = "Number of positive samples", x = "Study week", fill = "Virus") +
  theme_custom() +
  coord_cartesian(clip = "off") +
  theme(panel.grid = element_blank(),
        panel.spacing.x = unit(1, "cm"),
        axis.title.x = element_text(color = "white"),
        legend.position = "none",
        plot.title.position = "plot") +
  guides(fill = guide_legend(nrow = 1))

pos_week_pl
```

```{r}
# positive samples by study condition
df_pos_stud <- df_pos %>%
  group_by(aircleaner) %>%
  summarize(n_pos = sum(n)) %>%
  ungroup() %>%
  mutate(aircleaner = factor(aircleaner, levels = c("No", "Yes")))
  
pos_cond_pl <- df_pos_stud %>%
  ggplot(aes(x = aircleaner, y = n_pos)) +
  geom_bar(mapping = aes(fill = aircleaner), stat = "identity", color = "black", width = .4) +
  geom_text(mapping = aes(label = n_pos), size = 8 / cm(1), vjust = -1) +
  geom_segment(data = data.frame(x = 1, xend = 1, y = 30, yend = 29), mapping = aes(x = x, xend = xend, y = y, yend = yend), color = "white") +
  ggsignif::geom_signif(annotations = "PP(Yes<No) = 65%", y_position = 28, xmin = 1, xmax = 2, 
                        textsize = 8 / cm(1), vjust = -.5) +
  labs(x = "Air cleaner", y = "Number of positive saliva samples", title = "a") +
  scale_fill_manual(values = wes_palette("Royal1")[1:2]) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)), breaks = scales::pretty_breaks(4)) +
  theme_custom() +
  theme(plot.title.position = "plot") +
  guides(fill = "none")

pos_cond_pl

save_plot(pos_cond_pl, 
          "../results/mol-data/saliva-by-study-condition.pdf",
          "../results/mol-data/saliva-by-study-condition.eps",
          w = 7.25, h = 6)
```

```{r}
# Total counts by virus
df_pos_tot <- df_pos %>%
  group_by(variable) %>%
  summarize(n = sum(n)) %>%
  ungroup()

pos_tot_pl <- ggplot(mapping = aes(y = n, x = 1, fill = variable)) +
  geom_bar(data = df_pos_tot, stat = "identity", position = position_stack(reverse = T), width = .5) +
  geom_text(data = df_pos_tot %>% mutate(n_lab = paste0(variable, ": ", n)), 
            mapping = aes(label = n_lab), 
            size = 8 / cm(1), position = position_stack(vjust = 0.5, reverse = T), color = "white") +
  scale_fill_manual(values = wes_palette("IsleofDogs1")) +
  scale_color_manual(values = wes_palette("IsleofDogs1")) +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = expansion(mult = c(0.1,0.3))) +
  labs(y = "Number of positive samples", fill = "Virus", title = "a") +
  theme_custom() +
  theme(panel.grid = element_blank(),
        plot.title.position = "plot",
        legend.position = "none",
        # legend.title = element_blank(),
        # legend.key.width = unit(.3, "cm"),
        # legend.key.height = unit(.1, "cm"),
        axis.title.x = element_blank(),
        axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  guides(fill = guide_legend(nrow = 1))

pos_tot_pl

save_plot(pos_tot_pl, 
          "../results/mol-data/saliva-distribution.pdf",
          "../results/mol-data/saliva-distribution.eps",
          w = 3.25, h = 20)
```

<!-- ```{r} -->
<!-- # combine -->
<!-- descr <- pos_tot_pl + plot_spacer() + pos_cond_pl & theme(legend.position = "bottom", legend.key.height = unit(.1, "cm"), -->
<!--                                           legend.key.width = unit(.3, "cm")) -->
<!-- descr <- descr + plot_layout(guides = "collect", widths = c(9.5, 1, 5.5), ncol = 2)  -->
<!-- descr <- descr + pos_week_pl  -->
<!-- descr <- descr + plot_layout(nrow = 2, heights = c(8, 8), design = 'ABC -->
<!--                              DDD') -->
<!-- save_plot(descr, pdf_file = "../results/mol-data/descriptives.pdf", eps_file = "../results/mol-data/descriptives.eps", h = 16, w = 16) -->
<!-- # saveRDS(pos_tot_pl + ggtitle(""), file = "../results/mol-data/descriptives-total.rds") -->
<!-- # saveRDS(pos_cond_pl + ggtitle(""), file = "../results/mol-data/descriptives-cond.rds") -->
<!-- # saveRDS(pos_week_pl + ggtitle(""), file = "../results/mol-data/descriptives-week.rds") -->
<!-- ``` -->


### Transmission network

```{r}
tnet <- df_network %>%
  mutate(date_infection = as.POSIXct(paste0(date_infection, "00:00:00")),
         virus = ifelse(virus == "SARS-CoV-2", "CoV", virus),
         virus = factor(virus, levels = c("Flu B", "HRV", "AdV", "CoV", "MPV", "PIV")),
         class = paste("Class", class)) %>%
  group_by(id, class, date_infection, virus, chain) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(n = factor(n, levels = c(1,2,3))) %>%
  group_by(class, chain) %>%
  arrange(date_infection) %>%
  mutate(from = date_infection + hours(12),
         to = lead(date_infection) - hours(12)) %>%
  ungroup() 

coord_y_datetime <- function(xlim = NULL, ylim = NULL, expand = TRUE) {
  if (!is.null(ylim)) {
    ylim <- lubridate::as_datetime(ylim)
  }
  ggplot2::coord_cartesian(xlim = xlim, ylim = ylim, expand = expand)
}

mirror_scales <- list(scale_x_discrete(limits = rev), scale_x_discrete())

tnet_pl <- tnet %>%
  mutate(type = factor("Saliva", levels = c("Saliva", "Air", "Filter"))) %>%
  ggplot(aes(y = date_infection, x = virus, size = n, shape = type)) +
  facet_wrap(~ class, ncol = 2, scales = "free_x") +
  ggh4x::facetted_pos_scales(x = mirror_scales) +
  geom_point(data = air_samples %>% 
               mutate(date_infection = as.POSIXct(paste0(date, "00:00:00", format = "%d-%m-%Y %H:%M:%S")),
                      n = factor(1, levels = c(1,2,3)),
                      class = factor(paste("Class", class), levels = c("Class A", "Class B")),
                      type = factor(type, levels = c("Saliva", "Air", "Filter")),
                      virus = factor(virus, levels = c("Flu B", "HRV", "AdV", "CoV", "MPV", "PIV"))),
             mapping = aes(color = virus), fill = "white",
             position = position_dodge(width = -.85, preserve = "single")) +
  geom_point(mapping = aes(fill = virus), color = "black") +
  geom_segment(aes(y = from, yend = to, xend = virus), size = 1,
              arrow = arrow(length = unit(0.2, "cm")), color = "black") +
  labs(size = "Number of infections", fill = "Virus", shape = "", title = "b") +
  coord_y_datetime(ylim = c(max(tnet$date_infection), min(tnet$date_infection))) +
  scale_y_datetime(date_breaks = "1 week", date_labels = "%b %d") +
  scale_size_discrete(range = c(4,8)) +
  scale_fill_manual(values = wes_palette("IsleofDogs1")) +
  scale_color_manual(values = wes_palette("IsleofDogs1")) +
  scale_shape_manual(values = c("Saliva" = 21, "Air" = 22, "Filter" = 23),
                     breaks = c("Saliva", "Air", "Filter")) +
  theme_custom() +
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.box = "horizontal",
        plot.title.position = "plot",
        axis.title = element_blank(),
        panel.spacing = unit(.5, "cm"),
        panel.grid.major.x = element_line(),
        panel.grid.minor.y = element_blank(),
        strip.text.x = element_text(size = 10, margin = margin(b = 10))) +
  guides(fill = "none",
         color = "none",
         shape = guide_legend(order = 1),
         size = guide_legend(nrow = 1, order = 2))

save_plot(tnet_pl, 
          pdf_file = "../results/mol-data/network-plot.pdf", 
          eps_file = "../results/mol-data/network-plot.eps", 
          w = 12.25, h = 20)
```


## Prepare data

```{r}
create.stan_data <- function(dat) {
  
  # stan data list
  stan_data <- list()

  # dimensions
  stan_data$N <- nrow(dat) / 2
  stan_data$K <- 6 + 1
  stan_data$C <- 2

  # outcome
  stan_data$samples <- dat %>%
    arrange(class, date) %>%
    dplyr::select(Neg, AdV, `Flu B`, HRV, MPV, PIV, `SARS-CoV-2`) %>%
    as.matrix()

  # air cleaner indicator
  stan_data$aircleaner <- dat %>%
    arrange(class, date) %>%
    mutate(aircleaner = ifelse(aircleaner == "Yes", 1, 0)) %>%
    dplyr::select(aircleaner) %>%
    unlist()

  # class
  stan_data$schoolclass <- dat %>%
    arrange(class, date) %>%
    mutate(class = ifelse(class == "A", 0, 1)) %>%
    dplyr::select(class) %>%
    unlist()

  # susceptibles 
  stan_data$susceptibles <- dat %>%
    group_by(class) %>%
    arrange(date) %>%
    mutate(across(c(AdV, `Flu B`, HRV, MPV, PIV, `SARS-CoV-2`), ~ n_class - cumsum(.x)),
           across(c(AdV, `Flu B`, HRV, MPV, PIV, `SARS-CoV-2`), ~ (.x - mean(.x)) / sd(.x)),
           PIV = 0) %>% # no variation in PIV
    ungroup() %>%
    arrange(class, date) %>%
    dplyr::select(AdV, `Flu B`, HRV, MPV, PIV, `SARS-CoV-2`)

  return(stan_data)
}

stan_data <- create.stan_data(df)
```

## Modeling 

### Main model

```{r}
# stan model code file
stan_file <- "../models/multinomial-logit-model.stan"

# run model
multLogitMod <- stan(stan_file, data = stan_data, seed = 12345, cores = 4)

# quick estimation results
summary(multLogitMod, probs = c(0.025, 0.975), pars = c("beta0", "beta1", "beta2", "beta3"))$summary %>%
  data.frame() %>%
  mutate_all(round, 2)

# estimated effect of air cleaners
spread_draws(multLogitMod, beta1) %>%
  mutate(beta1 = exp(beta1)) %>%
  mean_qi()

# posterior probability
spread_draws(multLogitMod, beta1) %>%
  summarize(round(sum(beta1 < 0) / n() * 100))
```


### Sensitivity 

```{r}
# lag data by one test date and one week
df_l1d <- df %>%
  group_by(class) %>%
  mutate(aircleaner = lag(aircleaner),
         aircleaner = ifelse(is.na(aircleaner), "No", aircleaner)) %>%
  ungroup()

df_l1w <- df %>%
  group_by(class) %>%
  mutate(aircleaner = lag(aircleaner, 2),
         aircleaner = ifelse(is.na(aircleaner), "No", aircleaner)) %>%
  ungroup()

# stan data list
stan_data_l1d <- create.stan_data(df_l1d)
stan_data_l1w <- create.stan_data(df_l1w)

# model
multLogitMod_l1d <- stan(stan_file, data = stan_data_l1d, seed = 12345, cores = 4)
multLogitMod_l1w <- stan(stan_file, data = stan_data_l1w, seed = 12345, cores = 4)
```

## Results

```{r}
# lag types
lag_types <- c("None",
               "1 test date",
               "1 test week")

# collect draws
main_res <- spread_draws(multLogitMod, beta1)
sens_res_l1d <- spread_draws(multLogitMod_l1d, beta1)
sens_res_l1w <- spread_draws(multLogitMod_l1w, beta1)
res <- rbind(
  main_res %>% mutate(lag = lag_types[1]),
  sens_res_l1d %>% mutate(lag = lag_types[2]),
  sens_res_l1w %>% mutate(lag = lag_types[3])
) %>%
  mutate(beta1 = exp(beta1)) 

# plot
res_pl <- res  %>%
  ggplot() +
  stat_pointinterval(aes(x = beta1, y = lag), point_fill = "white", shape = 21, point_size = 3, .width = c(0.5, 0.8, 0.95)) +
  geom_vline(aes(xintercept = 1), linetype = "dashed") +
  scale_x_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0)), breaks = seq(0, 2, .25)) +
  scale_size_continuous(range = c(1, 9)) +
  labs(x = "Relative risk", y = "Lag of sampling results", fill = "CrI") +
  theme_custom() +
  theme(legend.position = "top", legend.direction = "horizontal",
        legend.key.height = unit(.25, "cm"), legend.key.width = unit(.35, "cm"))
res_pl
save_plot(res_pl, pdf_file = "../results/mol-data/model-results.pdf", w = 10, h = 6)
```
