---
title: "Study Comparison"
author: "Nicolas Banholzer"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(reshape2)
source("../utils/epi.r")
source("../utils/bayes.r")
source("../utils/plotting.r")
source("../utils/tex.r")
```


## Virus distribution

```{r}
saliva <- data.frame(
    year_num = c(rep(2022, 6), rep(2023, 6)),
    virus = rep(c("Flu", "HRV", "AdV", "CoV", "MPV", "PIV"), 2),
    n = c(c(1, NA, 1, 19, NA, NA), c(15, 15, 14, 3, 2, 1))
  ) %>%
  mutate(year = ifelse(year_num == 2022, "Winter 2021/2022", "Winter 2022/2023"),
         year = factor(year, levels = c("Winter 2021/2022", "Winter 2022/2023")),
         virus = factor(virus, levels = c("Flu", "HRV", "AdV", "CoV", "MPV", "PIV"))) %>%
  filter(!is.na(n)) %>%
  group_by(year) %>%
  arrange(virus) %>%
  mutate(p = n / sum(n, na.rm = T),
         ymax = cumsum(p),
         ymin = lag(ymax, n = 1),
         ymin = ifelse(is.na(ymin), 0, ymin),
         labelPosition = (ymax + ymin) / 2,
         label = paste0(virus, ": ", n)) %>%
  ungroup() %>%
  mutate(labelPosition = ifelse(year == "Winter 2022/2023" & virus == "MPV", labelPosition - .015, labelPosition),
         labelPosition = ifelse(year == "Winter 2021/2022" & virus == "Flu", ymin, labelPosition),
         labelPosition = ifelse(year == "Winter 2021/2022" & virus == "AdV", ymax, labelPosition))

saliva_pl <- saliva %>%
  ggplot() +
  facet_wrap(~ year_num, nrow = 1) +
  geom_rect(mapping = aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = virus)) +
  geomtextpath::coord_curvedpolar(theta = "y", start = 1.9*pi) +
  geom_text(mapping = aes(x = 5.25, y=labelPosition, label=label, color=virus), size = 8/cm(1)) +
  geom_text(data = data.frame(x = 1, y = 1, year_num = c(2022, 2023), label = c(2022, 2023)), mapping = aes(x = x, label = label, y = y), 
            size = 8/cm(1), fontface = 2) +
  scale_x_continuous(limits = c(1, 5.25), expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0),  position = "top") +
  scale_fill_manual(values = RColorBrewer::brewer.pal(9, "BuPu")[4:9]) +
  scale_color_manual(values = RColorBrewer::brewer.pal(9, "BuPu")[4:9]) +
  ggtitle("a") +
  theme_void() +
  theme(legend.position = "none",
        plot.title = element_text(size = 10, face = 2),
        plot.title.position = "plot",
        legend.key.height = unit(.1, "cm"),
        legend.key.width = unit(.3, "cm"),
        strip.text = element_blank()) +
  guides(fill = guide_legend(nrow = 1),
         color = "none")

saliva_pl
```


## No. of positive samples

```{r}
pos_samples <- data.frame(
  year_num = factor(c(rep(2022, 3), rep(2023, 3)), levels = c(2022, 2023)),
  type = factor(rep(c("Saliva", "Bioaerosols", "HEPA-filter"), times = 2), levels = c("Saliva", "Bioaerosols", "HEPA-filter")),
  n_pos = c(c(21, 10, 8), c(50, 2, 4)),
  n_tot = c(c(262, 130, 40), c(448, 105, 160))
) %>%
  mutate(n_neg = n_tot - n_pos,
         year = ifelse(year_num == 2022, "Winter 2021/2022", "Winter 2022/2023"),
         year = factor(year, levels = c("Winter 2021/2022", "Winter 2022/2023"))) %>%
  dplyr::select(-n_tot,-n_neg) %>%
  reshape2::melt(c("year_num", "year", "type"))

pos_samples_pl <- pos_samples %>%
  ggplot(aes(y = value, x = year_num, fill = year)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = value, color = year), size = 8 / cm(1), vjust = -1) +
  facet_wrap(~ type, nrow = 1) +
  scale_y_continuous(expand = expansion(add = c(0,5))) +
  scale_fill_manual(values = RColorBrewer::brewer.pal(11, "BrBG")[c(4,8)]) +
  scale_color_manual(values = RColorBrewer::brewer.pal(11, "BrBG")[c(4,8)]) +
  labs(y = "Frequency of positive samples", title = "b") +
  theme_custom() +
  theme(legend.position = "none",
        plot.title.position = "plot",
        strip.text = element_text(face = 2, vjust = 2, margin = margin(t = 10, b = 10)),
        panel.spacing.x = unit(1, "cm"),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

pos_samples_pl
```

```{r}
comparison <- grid.arrange(saliva_pl, pos_samples_pl, nrow = 2, heights = c(6, 8), widths = 11)
ggsave(plot = comparison, file = "../results/comparison.pdf", width = 11.5 / cm(1), height = 14 / cm(1))
```


<!-- ## Particle reduction -->

<!-- ```{r} -->
<!-- vars <- c("CO2", "rH", "Temp", "AER", "Cn", "PM1", "PM25", "PM4", "PM10") -->
<!-- vars_labels_no_units <- c("CO[2]", "Relative~humidity", "Temperature", "Air~exchange~rate", -->
<!--                           "CN", "PM[1]", "PM[2.5]", "PM[4]", "PM[10]") -->
<!-- names(vars_labels_no_units) <- vars -->

<!-- particle <- data.frame( -->
<!--   year = factor(c(rep(2022, 15), rep(2023, 15)), levels = c(2022, 2023)), -->
<!--   variable = factor(c(rep(c("Cn", "PM1", "PM25", "PM4", "PM10"), each = 3, times = 2)), levels = c("Cn", "PM1", "PM25", "PM4", "PM10")), -->
<!--   interval = rep(c("Mean", "Lower", "Upper"), times = 5), -->
<!--   estimate = c(c(39.24, 3.88, 68.80,  -->
<!--                  41.05, 6.62, 67.98, -->
<!--                  45.12, 19.66, 63.16, -->
<!--                  46.49, 27.26, 61.72, -->
<!--                  46.60, 29.99, 59.49), -->
<!--                c(76.83, 63.20, 86.28, -->
<!--                  76.79, 64.84, 85.46, -->
<!--                  72.86, 64.24, 79.66, -->
<!--                  70.77, 63.46, 76.97, -->
<!--                  99.99, 99.94, 100.00)) -->
<!-- ) %>% -->
<!--   dcast(year + variable ~ interval) %>% -->
<!--   ggplot(aes(y = year, color = year)) + -->
<!--   facet_wrap(~ variable, nrow = 1, dir = "h", labeller = as_labeller(vars_labels_no_units, label_parsed)) + -->
<!--   geom_errorbar(mapping = aes(xmin = Lower, xmax = Upper), lineend = "square", size = 1, width = .05) + -->
<!--   geom_point(mapping = aes(x = Mean), shape = 23, size = 2, fill = "white") + -->
<!--   scale_color_manual(values = wes_palette("Darjeeling2")[c(2, 5)]) + -->
<!--   scale_x_continuous(expand = expansion(mult = c(0, 0.1)), breaks = c(0, 50, 100), limits = c(0, 100)) + -->
<!--   labs(y = "Study year", x = "Estimated reduction in particle concentration (%)", title = "c") +  -->
<!--   theme_custom() + -->
<!--   theme(legend.position = "none", -->
<!--         plot.title.position = "plot", -->
<!--         panel.spacing = unit(.5, "lines")) -->

<!-- particle -->
<!-- ``` -->


<!-- ## Risk ratio -->

<!-- ```{r} -->
<!-- rr <- data.frame( -->
<!--   year = factor(c(rep(2022, 3), rep(2023, 3)), levels = c(2022, 2023)), -->
<!--   interval = rep(c("Mean", "Lower", "Upper"), times = 2), -->
<!--   estimate = c(c(1.00, 0.22, 2.067), c(0.72, 0.44, 1.15)) -->
<!-- ) %>% -->
<!--   dcast(year ~ interval) %>% -->
<!--   ggplot(aes(y = year, color = year)) + -->
<!--   geom_vline(aes(xintercept = 1), linetype = "dashed") + -->
<!--   geom_errorbar(mapping = aes(xmin = Lower, xmax = Upper), lineend = "square", size = 1, width = .05) + -->
<!--   geom_point(mapping = aes(x = Mean), shape = 23, size = 2, fill = "white") + -->
<!--   labs(y = "Study year", x = "ARR of infection with air cleaners (%)", title = "d") +  -->
<!--   scale_color_manual(values = wes_palette("Darjeeling2")[c(2, 5)]) + -->
<!--   theme_custom() + -->
<!--   theme(legend.position = "none", -->
<!--         plot.title.position = "plot") -->

<!-- rr   -->
<!-- ``` -->


<!-- ## Combined  -->

<!-- ```{r} -->
<!-- comparison <- grid.arrange(saliva, pos_samples, particle, rr, ncol = 2, nrow = 2, heights = c(6, 4), widths = c(10,6)) -->
<!-- ggsave(plot = comparison, file = "../results/comparison.pdf", width = 16 / cm(1), height = 10 / cm(1)) -->
<!-- ``` -->